[General]
network = src.RemoteExecutionNetwork
sim-time-limit = 300s
cpu-time-limit = 600s
debug-on-errors = true

# Graphics
record-eventlog = true
**.vector-recording = true
**.scalar-recording = true

# Output
cmdenv-express-mode = true
cmdenv-interactive = true 

# By B22CS061 & B22CS062