[General]
network = RemoteExecutionNetwork
sim-time-limit = 600s
cpu-time-limit = 300s
debug-on-errors = true

# Graphics
record-eventlog = true
**.vector-recording = true
**.scalar-recording = true

# Output
cmdenv-express-mode = false
cmdenv-interactive = true
cmdenv-message-trace = true
**.cmdenv-log-level = info
warmup-period = 2s

# By B22CS061 & B22CS062