// By B22CS061 & B22CS062
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/RemoteExecution.msg.
//

#ifndef __REMOTEEXECUTION_M_H
#define __REMOTEEXECUTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class BaseMessage;
class TaskMessage;
class ResultMessage;
class GossipMessage;
class RatingMessage;
/**
 * Class generated from <tt>src/RemoteExecution.msg:4</tt> by opp_msgtool.
 * <pre>
 * // Base message type
 * message BaseMessage
 * {
 *     string sourceId;     // ID of the sender
 *     string destinationId; // ID of the recipient
 *     int timestamp;       // Timestamp for ordering
 * }
 * </pre>
 */
class BaseMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sourceId;
    omnetpp::opp_string destinationId;
    int timestamp = 0;

  private:
    void copy(const BaseMessage& other);

  protected:
    bool operator==(const BaseMessage&) = delete;

  public:
    BaseMessage(const char *name=nullptr, short kind=0);
    BaseMessage(const BaseMessage& other);
    virtual ~BaseMessage();
    BaseMessage& operator=(const BaseMessage& other);
    virtual BaseMessage *dup() const override {return new BaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSourceId() const;
    virtual void setSourceId(const char * sourceId);

    virtual const char * getDestinationId() const;
    virtual void setDestinationId(const char * destinationId);

    virtual int getTimestamp() const;
    virtual void setTimestamp(int timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BaseMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/RemoteExecution.msg:11</tt> by opp_msgtool.
 * <pre>
 * // Task message from client to server
 * message TaskMessage extends BaseMessage
 * {
 *     int taskId;          // Unique ID for the task
 *     int subtaskId;       // ID of the subtask
 *     int values[];        // Array of integers for the subtask
 * }
 * </pre>
 */
class TaskMessage : public ::BaseMessage
{
  protected:
    int taskId = 0;
    int subtaskId = 0;
    int *values = nullptr;
    size_t values_arraysize = 0;

  private:
    void copy(const TaskMessage& other);

  protected:
    bool operator==(const TaskMessage&) = delete;

  public:
    TaskMessage(const char *name=nullptr, short kind=0);
    TaskMessage(const TaskMessage& other);
    virtual ~TaskMessage();
    TaskMessage& operator=(const TaskMessage& other);
    virtual TaskMessage *dup() const override {return new TaskMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual void setValuesArraySize(size_t size);
    virtual size_t getValuesArraySize() const;
    virtual int getValues(size_t k) const;
    virtual void setValues(size_t k, int values);
    virtual void insertValues(size_t k, int values);
    [[deprecated]] void insertValues(int values) {appendValues(values);}
    virtual void appendValues(int values);
    virtual void eraseValues(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/RemoteExecution.msg:18</tt> by opp_msgtool.
 * <pre>
 * // Result message from server to client
 * message ResultMessage extends BaseMessage
 * {
 *     int taskId;          // Corresponding task ID
 *     int subtaskId;       // Corresponding subtask ID
 *     int result;          // Result of the computation (e.g., maximum value)
 *     bool isValid = true; // Flag to indicate if result is valid (honest) or not (malicious)
 * }
 * </pre>
 */
class ResultMessage : public ::BaseMessage
{
  protected:
    int taskId = 0;
    int subtaskId = 0;
    int result = 0;
    bool isValid_ = true;

  private:
    void copy(const ResultMessage& other);

  protected:
    bool operator==(const ResultMessage&) = delete;

  public:
    ResultMessage(const char *name=nullptr, short kind=0);
    ResultMessage(const ResultMessage& other);
    virtual ~ResultMessage();
    ResultMessage& operator=(const ResultMessage& other);
    virtual ResultMessage *dup() const override {return new ResultMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual int getResult() const;
    virtual void setResult(int result);

    virtual bool isValid() const;
    virtual void setIsValid(bool isValid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResultMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResultMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/RemoteExecution.msg:26</tt> by opp_msgtool.
 * <pre>
 * // Gossip message for score propagation
 * message GossipMessage extends BaseMessage
 * {
 *     string content;      // Content in format <timestamp>:<IP>:<Score>
 *     bool firstTime;      // Whether this is the first time receiving this message
 * }
 * </pre>
 */
class GossipMessage : public ::BaseMessage
{
  protected:
    omnetpp::opp_string content;
    bool firstTime = false;

  private:
    void copy(const GossipMessage& other);

  protected:
    bool operator==(const GossipMessage&) = delete;

  public:
    GossipMessage(const char *name=nullptr, short kind=0);
    GossipMessage(const GossipMessage& other);
    virtual ~GossipMessage();
    GossipMessage& operator=(const GossipMessage& other);
    virtual GossipMessage *dup() const override {return new GossipMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getContent() const;
    virtual void setContent(const char * content);

    virtual bool getFirstTime() const;
    virtual void setFirstTime(bool firstTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GossipMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GossipMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/RemoteExecution.msg:32</tt> by opp_msgtool.
 * <pre>
 * // Rating message for server evaluation
 * message RatingMessage extends BaseMessage
 * {
 *     int serverId;        // ID of the server being rated
 *     double rating;       // Rating value
 * }
 * </pre>
 */
class RatingMessage : public ::BaseMessage
{
  protected:
    int serverId = 0;
    double rating = 0;

  private:
    void copy(const RatingMessage& other);

  protected:
    bool operator==(const RatingMessage&) = delete;

  public:
    RatingMessage(const char *name=nullptr, short kind=0);
    RatingMessage(const RatingMessage& other);
    virtual ~RatingMessage();
    RatingMessage& operator=(const RatingMessage& other);
    virtual RatingMessage *dup() const override {return new RatingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getServerId() const;
    virtual void setServerId(int serverId);

    virtual double getRating() const;
    virtual void setRating(double rating);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RatingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RatingMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline BaseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<BaseMessage*>(ptr.get<cObject>()); }
template<> inline TaskMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<TaskMessage*>(ptr.get<cObject>()); }
template<> inline ResultMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<ResultMessage*>(ptr.get<cObject>()); }
template<> inline GossipMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<GossipMessage*>(ptr.get<cObject>()); }
template<> inline RatingMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<RatingMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REMOTEEXECUTION_M_H

